spring.datasource.url=jdbc:mysql://mysql:3306/medical_records?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

spring.security.oauth2.client.registration.keycloak.client-id=medical-records-app
spring.security.oauth2.client.registration.keycloak.client-secret=v7ktoVnMHq2ygQBsBsYjQkC0gFgaUpVq
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8084/login/oauth2/code/keycloak

spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8080/realms/medical-records/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=http://keycloak:8080/realms/medical-records/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://keycloak:8080/realms/medical-records/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://keycloak:8080/realms/medical-records/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/medical-records/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/medical-records